Simple script to extract a single version (#8)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,4 +21,22 @@ jobs:
       - uses: actions/checkout@v2
       - uses: ./
         with:
-          milliseconds: 1000
+          version: 0.0.1
+      - uses: actions/checkout@v2
+      - uses: ./
+        id: run3
+        with:
+          filename: test_changelogs/CHANGELOG.md
+          version: 0.0.3
+      - name: check version 3
+        env:
+          OUT3: ${{steps.run3.outputs.body}}
+        run: |
+          if [[ $OUT3 == $(cat test_changelogs/v3-body.md) ]] 
+            then 
+              echo "match!"
+          else 
+              echo "::error ::no match - [${OUT3}]"
+              exit 1
+          fi
+
